### ISSUE TITLE
License and some minors

### ISSUE THREAD

**Issue by IzzySoft** [DrMint/Litrato#1]
This is quite a well-documented project if I ever saw one, congrats! And even only skimming the Readme is promising. A few questions however:

* What license are you using?
* the tag says "1.0" – but the APK identifies as "1.1"; is that intended?
* seeing `versionName "1.1"` together with `versionCode 1` looks like the latter was forgotten to increase (but could also mean you just started with "1.1" because noone would trust a .0 release)?
* as this is an open-source project, wouldn't you rather use an open-source mapping library ([OSM](https://github.com/osmdroid/osmdroid)?) instead of bringing in proprietary dependencies (here: Google Maps and GSM)?

Thanks in advance for letting me know!

**Comment by DrMint** [comment]
Hi, I'm glad you've found our program promising. It was a school project, so we made sure to properly document everything!

- So about the license, we will go for a permissive license, most likely MIT. I will consult the other collaborators about this.

- You are right. I fixed it.

- I'm not sure why we ended up with those version numbers, it's definitely not something we took very seriously.

- Yes, we should have done this. The Exif-viewer function wasn't something required by the specification we were given, it was a fun side-project we ended up integrating in the program. I'll check OSM when I can, but I have been quite busy recently.

Thanks for the feedback!

**Comment by IzzySoft** [comment]
Thanks for your response! Looking forward to the updates then. Another note on versioning (in case you know this already, feel free to ignore): while `versionName` is what is shown to the "human", `versionCode` is what Android itself uses to tell versions apart. So unless an APK has a higher `versionCode`, Android won't accept it as "update". Which is why it's important to always increase it with each new release.

And no pressure: it's done when you have time. I know what it means to be busy, same problem here :wink:
