### ISSUE TITLE
Can't open an image from my local storage

### ISSUE THREAD

**Issue by masslesssonny** [DrMint/Litrato#3]
Using release 1.1 APK, I am unable to open an image from the local storage of my phone. 

The app lets me open the gallery viewer and when I select an image it goes back to the Litrato interface but the test image is still present. I have tried to open images from various locations on my phone to no avail.

Clicking on take picture also does not do anything so at the moment I can only edit the test image. The functionality of the application looks awesome, would be very keen to try with my own images.

**Comment by DrMint** [comment]
Hi, thank you for the feedback.

I was aware of the problem, it believe it has to do with the way Android 10 and up handles storage access.
Could you share some information about you're phone, especially the Android version?

**Comment by DrMint** [comment]
I just pushed a new release, version 1.11. Can you try it on your phone? Thanks in advance.
