### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 22360 (e.retouchephoto)   am getting this error on just launching app 

### ISSUE THREAD

**Issue by waqasyousafy** [DrMint/Litrato#6]
I want to set the minisdkversion 21 and after launching the it crashes everytime
please help me

**Comment by DrMint** [comment]
Hi! I'm not surprised by this behavior. I'm guessing you wanted to install it on an android device running Android 5.0 Lollipop, while the app was developed for Android 8.0 Oreo and onward. Unfortunately, making an app backward compatible with previous versions of Android is not as straightforward as changing the minSdkVersion. I don't remember exactly what APIs we used for Litrato but I'm sure the way we access files and take picture isn't compatible with the way older Android devices operates.

I do not intend on making the app compatible with versions older than Oreo, I'll only try to maintain compatibility with future releases of Android. If you're able to make it work with minSdkVersion 21, feel free to make a pull request.
