### ISSUE TITLE
Compiled *Not* For Debug?

### ISSUE THREAD

**Issue by MadManMoon** [DrMint/Litrato#7]
Hi there.

This looks amazing, but given the potential access implications after the fact, will there be a version on izzysoft that is not compiled for debugging?

Not asking with any entitlement, or expectation of response, just thought it might be something to up the security profile of it is all.

Keep up the good work!

**Comment by DrMint** [comment]
I never really looked into it, but I'm sure it's not difficult to do. I'll update the apk whenever I can. Thanks for your kind words and for opening the issue :)

**Comment by MadManMoon** [comment]
My pleasure, mate, happy to say them!

**Comment by MadManMoon** [comment]
Sorry, didn't mean to close this, it may have de-assigned it. Apologies!

**Comment by Decodex-ray** [comment]
It's dead now
